### PR TITLE
Update version to 3.0.0

### PR DESCRIPTION
**Pull request by gliavallo**
With this PR we:
1. Added support for Elixir 1.15 and Erlang 25.3.
2. Dropped support for Elixir 1.12.
3. Replaced `warn` calls with `warning` calls.
4. Removed `ex_statsd` dependency.
5. Bumped app version to 3.0.0.

MED-679

### CODE REVIEW

**Comment by kmteras** [comment]
Technically, this change is not backwards compatible for Elixir 1.10 and below as there was no `:warning` keyword then.
Could bump to `3.0.0` because if that but I think having it be bumped to `2.5.0` is also fine

**Comment by gliavallo** [comment]
> Technically, this change is not backwards compatible for Elixir 1.10 and below as there was no `:warning` keyword then. Could bump to `3.0.0` because if that but I think having it be bumped to `2.5.0` is also fine

I bumped it to `2.5.0` because we officially support Elixir 1.12+.

**Comment by take-five** [comment]
> because we officially support Elixir 1.12+.

Should we? Elixir 1.12 has reached EOL: https://endoflife.date/elixir

**Review by ostap0207 — APPROVED** [review]

**Comment by gliavallo** [comment]
> > because we officially support Elixir 1.12+.
> 
> Should we? Elixir 1.12 has reached EOL: https://endoflife.date/elixir

From the provided link, I see that security updates are still provided to 1.12.
It also shows, that active support is available for 1.16+ only.

I'm not against the idea to drop support for some older versions.

**Comment by gliavallo** [comment]
And if we do decide to drop support for older Elixir versions, where should the cutoff be?

**Comment by take-five** [comment]
We don't have to keep support for all Elixir versions on all new versions of this library.
We can say that the library supports only 2-3 latest versions of Elixir, and security patches are backported into the older versions of the library. For example, we drop support for Elixir 1.12 from version 2.5. 6 months later, we issue a security patch - version 2.5.1, and backport it to 2.4.x well.

**Review by take-five — APPROVED** [review]

**Comment by gliavallo** [comment]
!merge

**Comment by gliavallo** [comment]
This broke the publishing. Need to find a way to fix it.
Publisher is Docker container with Elixir version 1.11.
As we updated minimum version for our app, it does not run any more.

**Pull request merged**
